export enum ActionTypes {
    CHANGE_NAME_VALUE = "CHANGE_NAME_VALUE",
    CHANGE_EMAIL_VALUE = "CHANGE_EMAIL_VALUE",
    CHANGE_SUBJECT_VALUE = "CHANGE_SUBJECT_VALUE",
    CHANGE_MESSAGE_VALUE = "CHANGE_MESSAGE_VALUE",
    CHANGE_NAME_LABEL = "CHANGE_NAME_LABEL",
    CHANGE_EMAIL_LABEL = "CHANGE_EMAIL_LABEL",
    CHANGE_SUBJECT_LABEL = "CHANGE_SUBJECT_LABEL",
    CHANGE_MESSAGE_LABEL = "CHANGE_MESSAGE_LABEL",
}