export enum ActionTypes {
    SET_REACT_FILTER = "SET_REACT_FILTER",
    SET_ANGULAR_FILTER = "SET_ANGULAR_FILTER",
    SET_FRAMER_MOTION_FILTER = "SET_FRAMER_MOTION_FILTER",
    SET_JAVASCRIPT_FILTER = "SET_JAVASCRIPT_FILTER",
    SET_TYPESCRIPT_FILTER = "SET_TYPESCRIPT_FILTER",
    SET_JAVA_FILTER = "SET_JAVA_FILTER",
    SET_NEXT_FILTER = "SET_NEXT_FILTER",
    SET_NODE_FILTER = "SET_NODE_FILTER",
    SET_NEST_FILTER = "SET_NEST_FILTER",
    SET_SPRING_FILTER = "SET_SPRING_FILTER",
}